# Generated by Django 5.0.6 on 2024-07-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resivermodel',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
