# Generated by Django 5.0.6 on 2024-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resiver', '0002_resivermodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resivermodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
