# Generated by Django 5.0.6 on 2024-08-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donermodel',
            old_name='user',
            new_name='sender',
        ),
    ]
