# Generated by Django 5.0.6 on 2024-10-15 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doner', '0002_rename_user_donermodel_sender'),
        ('resiver', '0005_alter_resivermodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donermodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resiver.resivermodel'),
        ),
        migrations.AlterField(
            model_name='donermodel',
            name='resiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donermodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
