# Generated by Django 5.1.5 on 2025-02-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='text',
            field=models.TextField(max_length=100000),
        ),
    ]
